#!/bin/bash

# See: https://docs.openshift.org/latest/getting_started/administrators.html#running-in-a-docker-container

# Available versions: https://hub.docker.com/r/openshift/origin/tags/
OPENSHIFT_VERSION=3.7.1
#OPENSHIFT_VERSION=3.9.0

# Vagrant's public network is on eth1
# See: # https://askubuntu.com/a/560466
PUBLIC_IP=$(ip addr show eth1 | grep 'inet\b' | awk '{print $2}' | cut -d/ -f1)
MASTER="https://$PUBLIC_IP:8443"

sudo docker run \
	--name=origin \
	--privileged \
	--restart=always \
	--detach \
	--pid=host \
	--network=host \
	--volume=/:/rootfs:ro \
	--volume=/var/run:/var/run:rw \
	--volume=/sys:/sys \
	--volume=/sys/fs/cgroup:/sys/fs/cgroup:rw \
	--volume=/var/lib/docker:/var/lib/docker:rw \
	--volume=/var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes:rslave \
	--volume=/home/vagrant/host/container:/var/lib/origin/container \
	"openshift/origin:v$OPENSHIFT_VERSION" start --master="$MASTER"

echo "Waiting for OpenShift to start..."
sleep 10

sudo docker exec origin /var/lib/origin/container/install-templates

echo "Access OpenShift web console at: $MASTER/console/"
echo "Note that you will have to add a security exception for the cert in your web browser"
echo "Default username: admin, password: admin"
