#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")

# Do we really need to update all packages? Takes forever...
#dnf update -y

dnf install -y docker byobu

# Byobu makes ssh-ing easier
sudo -u vagrant byobu-enable

# Docker
systemctl enable docker
systemctl start docker

# Disable the firewall so we can access OpenShift from outside the VM
# TODO: just open port we want (8443 for OpenShift and other application ports)
systemctl disable firewalld
systemctl stop firewalld

# Bootstrap OpenShift
"$HERE/bootstrap-openshift"
