#!/bin/bash
set -e

# To get the latest version of the templates, delete the "templates" directory

# See: https://docs.openshift.org/latest/install_config/imagestreams_templates.html

HERE=$(dirname "$(readlink -f "$0")")
TEMPLATES="$HERE/templates"

# Translate the version from something like "v3.7.1+ab0f056" to "3.7"
OPENSHIFT_VERSION=$(openshift version | grep 'openshift\b' | awk '{split($2,v,"+"); split(substr(v[1],2),v,"."); print v[1] "." v[2]}')

if [ ! -d "$TEMPLATES" ]; then
	if [ ! -d /tmp/openshift-ansible ]; then 
		git clone --depth 1 https://github.com/openshift/openshift-ansible /tmp/openshift-ansible
	fi
	cp --recursive "/tmp/openshift-ansible/roles/openshift_examples/files/examples/v$OPENSHIFT_VERSION" "$TEMPLATES"
	rm --recursive --force /tmp/openshift-ansible

fi

# Streams
oc create --filename="$TEMPLATES/image-streams/image-streams-centos7.json" --namespace=openshift
#oc create --filename="$TEMPLATES/xpaas-streams" --namespace=openshift

# Templates
oc create --filename="$TEMPLATES/quickstart-templates" --namespace=openshift
oc create --filename="$TEMPLATES/db-templates" --namespace=openshift
#oc create --filename="$TEMPLATES/cfme-templates" --namespace=openshift
#oc create --filename="$TEMPLATES/xpaas-templates" --namespace=openshift
